### ISSUE TITLE
Multiple containers of elassandra 

### ISSUE THREAD

**Issue by boeyeb** [strapdata/docker-elassandra#10]
How can multiple containers can be deployed?

**Comment by DBarthe** [comment]
This docker image `strapdata/cassandra` is almost the same than the official cassandra image.
You'll find documentation there : https://github.com/docker-library/docs/tree/master/cassandra

**Comment by DBarthe** [comment]
During development and testing you can easily connect multiple containers to create an ephemeral cluster, just follow the documentation chapter ["Make a cluster"](https://github.com/docker-library/docs/tree/master/cassandra#make-a-cluster).

For always-on or production clusters, you should use kubernetes. A short guide available on [kubernetes-elassandra](https://github.com/strapdata/kubernetes-elassandra)
