### ISSUE TITLE
how to specify Xmx Xms  Java options?

### ISSUE THREAD

**Issue by hleb-albau** [strapdata/docker-elassandra#11]

**Comment by DBarthe** [comment]
In cassandra, both options are set according to the environment variable `MAX_HEAP_SIZE`.
If it's not set, it is computed to half of the system memory.

If you want distinct values for Xmx and Xms, you can override the default behavior by explicitly setting `JVM_OPTS="-Xmx4g -Xms2g"` in the docker env section.
