### ISSUE TITLE
Can't run nodetool inside container.

### ISSUE THREAD

**Issue by hleb-albau** [strapdata/docker-elassandra#12]
Running `nodetool` command inside container cause next error:
```
nodetool initial heap size is much than maximum
```

**Comment by lukaskeller** [comment]
stuck with the same thing. any updates on that issue?

**Comment by DBarthe** [comment]
Sorry guys. We are going to spend more time on the docker things now. Big refactoring is ongoing and bugs like this will be fixed soon.

**Comment by DBarthe** [comment]
Thinking about your problem, do you have a resources limit policy on your docker config ?

**Comment by DBarthe** [comment]
Hello,

Elassandra docker image has been refactored and improved with automation and testing.
The new image is available on docker hub starting from v6.2.3.7 and v5.5.0.24.

Please let me know if you still have the issue after upgrading, with information about the environment of your container (config, resources, load).

Thanks for your feedback

**Comment by DBarthe** [comment]
I close the issue because I consider it's fixed. Feel free to re-open it if necessary.
