### ISSUE TITLE
Default logs settings

### ISSUE THREAD

**Issue by hleb-albau** [strapdata/docker-elassandra#5]
By default, final image contains too high logs LVL. That results in no logs for even critical cases. All you see is 
```
Starting cassandra with org.apache.cassandra.service.ElassandraDaemon
Elassandra started
```

**Comment by DBarthe** [comment]
Hi @hleb-albau,

Within the container, logs are sent to `/var/cassandra/log/system.log`. To access you can run :
```
docker exec -it <container_id> less /var/cassandra/log/system.log
```
Or either bind mount the directory `/var/cassandra/log` and read the log file from the docker host.

Btw, the logging configuration is inherited from the upstream tar package (on github release page of elassandra)
If you want custom logging level and you use docker services, you can use [docker config](https://docs.docker.com/engine/swarm/configs/) feature to put a custom `logback.xml` in the container without having to rebuild your own image.

**Comment by hleb-albau** [comment]
Hi @DBarthe,

Yes, i already use exec to grap logs. 
But, what the reason to skip stoud?

**Comment by DBarthe** [comment]
I guess because of [this line](https://github.com/strapdata/elassandra/blob/v5.5.0-strapdata/distribution/src/main/resources/conf/logback.xml#L68). Don't know why it's commented out @vroyer ?

**Comment by hleb-albau** [comment]
Any updates?

**Comment by vroyer** [comment]
Barthelemy, 
Quel était le pb sur le logback.xml ? Il veut que le logging soit actif sur STDOUT par défaut quand elassandra est démarré en foreground ?
(Adresse moi ce genre de question directement plutôt que via le ticket, ça donne le sentiment qu’on travaille indépendamment).
A+,
Vincent.

**Comment by DBarthe** [comment]
It's solved now. The docker image has it own logback.xml with stdout elabled
